apiVersion: apps/v1
kind: Deployment
metadata:
  name: scripted-demo
  labels:
    app: sample
    role: leader
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
        role: leader
    spec:
      containers:
      - name: leader
        image: "arpan741/scripted-demo:latest"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379		
